name: Code Quality Check

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Check code formatting with black
        run: |
          black --check src/

      - name: Check import sorting with isort
        run: |
          isort --check-only src/

      - name: Run basic syntax check
        run: |
          python -m py_compile src/api/app.py
          python -m py_compile src/model/train.py
          python -m py_compile src/model/predict.py
          python -m py_compile src/data/data_preprocessing.py

      - name: Basic import test
        run: |
          python - <<'EOF'
          try:
              from src.data.data_preprocessing import DataPreprocessor
              from src.model.train import ModelTrainer
              print('✅ All imports successful')
          except Exception as e:
              print(f'❌ Import error: {e}')
              exit(1)
          EOF
